# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0002_auto_20171117_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taska',
            new_name='task',
        ),
    ]
