# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_auto_20171117_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='exam_app.User'),
        ),
    ]
