# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_auto_20171117_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasktime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
