# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_task_tasktime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
