# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_auto_20171117_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasktime',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
