# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_auto_20171117_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasktime',
            field=models.TimeField(),
        ),
    ]
