# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_auto_20171117_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newtaskname', models.CharField(max_length=255)),
                ('newtaskstatus', models.CharField(max_length=255)),
                ('newtasktime', models.TimeField(blank=True)),
                ('newtaskdate', models.DateTimeField(null=True)),
                ('newtask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newtasks', to='exam_app.User')),
            ],
        ),
    ]
